### PR TITLE
Fix Travis config to support PHP v5.3

### LINKED ISSUE #51: Fix Travis config to support PHP v5.3
We have [an error at Travis job](https://travis-ci.org/samdark/sitemap/jobs/306631737):
```
PHP 5.3 is supported only on Precise.
See https://docs.travis-ci.com/user/reference/trusty#PHP-images on how to test PHP 5.3 on Precise.
```

[Solution](https://docs.travis-ci.com/user/reference/trusty#PHP-images) is to add php 5.3 to matrix:
```
matrix:
  include:
    - php: 5.3
      dist: precise
```

### PR DESCRIPTION
**Pull request by terales**
Closes #51

### CODE REVIEW

**Comment by samdark** [comment]
Thanks. Seems we have PHP 5.4 arrays in tests. Would be great if you'd fixed that as well.

**Comment by terales** [comment]
Yep, wiil do

**Comment by terales** [comment]
Done

**Comment by samdark** [comment]
Thank you!

**Pull request merged**
